# Generated by Django 2.0 on 2018-03-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='onwer',
            new_name='owner',
        ),
    ]
