# Generated by Django 2.0 on 2018-03-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180330_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='data',
            new_name='json',
        ),
    ]
