# Generated by Django 2.0 on 2018-03-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180330_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='json',
            new_name='data',
        ),
    ]
