# Generated by Django 2.0 on 2018-01-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_membercard_tasks_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_tasks', '0003_auto_20180128_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedGroupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'GOALS'), (2, 'PROGRESS'), (3, 'ACTIVITIES'), (4, 'INTERRUPTIONS')])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_group_tasks', to='groups.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_group_tasks', to=settings.AUTH_USER_MODEL)),
                ('shared_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_group_tasks', to='group_tasks.SharedTask')),
            ],
        ),
    ]
