# Generated by Django 2.0 on 2018-03-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_uuid', models.CharField(max_length=32)),
                ('_assignment_info', models.TextField(db_column='assignment_info')),
            ],
        ),
    ]
