# Generated by Django 2.0 on 2018-03-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20180323_1418'),
        ('protected', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentinfo',
            name='assignment_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_infos', to='assignments.AssignmentProfile'),
            preserve_default=False,
        ),
    ]
