# Generated by Django 2.0 on 2018-03-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protected', '0002_assignmentinfo_assignment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentinfo',
            name='email',
            field=models.EmailField(default='unawares15@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentinfo',
            name='assignment_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_infos', to='assignments.AssignmentProfile'),
        ),
    ]
