# Generated by Django 2.0 on 2018-03-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected', '0003_auto_20180325_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentinfo',
            name='access',
            field=models.IntegerField(choices=[(1, 'EDIT'), (2, 'VIEW')], default=1),
            preserve_default=False,
        ),
    ]
