from django.utils.translation import ugettext_lazy as _


LABEL_PRIVATE = _('PRIVATE')
LABEL_PROTECTED= _('PROTECTED')
LABEL_PUBLIC = _('PUBLIC')

LABEL_GOALS = _('GOALS')
LABEL_PROGRESS = _('PROGRESS')
LABEL_ACTIVITIES = _('ACTIVITIES')
LABEL_INTERRUPTIONS = _('INTERRUPTIONS')
