# Generated by Django 2.0 on 2018-01-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetasks',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
