# Generated by Django 2.0 on 2018-03-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.CharField(max_length=32)),
                ('assignment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_profiles', to='assignments.AssignmentList')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('access', models.IntegerField(choices=[(1, 'PRIVATE'), (2, 'PROTECTED'), (3, 'PUBLIC')])),
                ('_key', models.TextField(db_column='key')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'GOALS'), (2, 'PROGRESS'), (3, 'ACTIVITIES'), (4, 'INTERRUPTIONS')])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedAssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assignment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_assignment_tasks', to='assignments.AssignmentTask')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_assignment_tasks_by', to='assignments.AssignmentProfile')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignmentlist',
            name='assignment_tasks',
            field=models.ManyToManyField(related_name='assignment_lists', to='assignments.AssignmentTask'),
        ),
        migrations.AddField(
            model_name='assignmentlist',
            name='assignments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_lists', to='assignments.Assignments'),
        ),
        migrations.AddField(
            model_name='assignmentlist',
            name='next_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_list', to='assignments.AssignmentList'),
        ),
        migrations.AddField(
            model_name='archivedassignmenttask',
            name='assignment_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_assignment_tasks', to='assignments.AssignmentTask'),
        ),
        migrations.AddField(
            model_name='archivedassignmenttask',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_assignment_tasks', to='assignments.AssignmentProfile'),
        ),
    ]
