# Generated by Django 2.0 on 2018-03-23 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
        migrations.RenameField(
            model_name='assignmentlist',
            old_name='assignments',
            new_name='assignment',
        ),
        migrations.AlterField(
            model_name='assignmentlist',
            name='next_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_list', to='assignments.AssignmentList'),
        ),
    ]
