# Generated by Django 2.0 on 2018-03-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20180323_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentprofile',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='completedassignmenttask',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_assignment_tasks', to='assignments.AssignmentProfile'),
        ),
    ]
