# Generated by Django 2.0 on 2018-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20180324_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='label_color',
            field=models.IntegerField(default=16777215),
        ),
    ]
