# Generated by Django 2.0 on 2018-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20180327_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='label_color',
            field=models.IntegerField(choices=[(1, 'GOALS'), (2, 'PROGRESS'), (3, 'ACTIVITIES'), (4, 'INTERRUPTIONS')]),
        ),
    ]
