# Generated by Django 2.0 on 2018-03-31 09:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20180327_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedassignmenttask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assignmenttask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='completedassignmenttask',
            options={},
        ),
        migrations.RemoveField(
            model_name='archivedassignmenttask',
            name='order',
        ),
        migrations.RemoveField(
            model_name='assignmenttask',
            name='order',
        ),
        migrations.RemoveField(
            model_name='completedassignmenttask',
            name='order',
        ),
        migrations.AddField(
            model_name='assignmentlist',
            name='orders',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
