# Generated by Django 2.0 on 2018-01-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180125_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='shared_task',
        ),
        migrations.RemoveField(
            model_name='membercard',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membercard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sharedtask',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sharedtask',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='sharedtask',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='sharedtask',
            name='previous',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupTask',
        ),
        migrations.DeleteModel(
            name='MemberCard',
        ),
        migrations.DeleteModel(
            name='SharedTask',
        ),
    ]
