# Generated by Django 2.0 on 2018-01-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180127_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercard',
            name='is_banned',
        ),
    ]
