# Generated by Django 2.0 on 2018-01-28 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_membercard_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercard',
            name='tasks_from',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
