# Generated by Django 2.0 on 2018-01-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_membercard_tasks_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercard',
            name='tasks_from',
        ),
    ]
