# Generated by Django 2.0 on 2018-01-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_membercard_tasks_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('created', 'updated')},
        ),
        migrations.AlterModelOptions(
            name='membercard',
            options={'ordering': ('created', 'updated')},
        ),
    ]
