# Generated by Django 2.0 on 2018-02-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20180129_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='membercard',
            options={'ordering': ('-created',)},
        ),
    ]
