# Generated by Django 2.0 on 2018-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20180323_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='flow',
            field=models.IntegerField(choices=[(1, 'One For Each'), (2, 'One For All')], default=1),
        ),
    ]
